<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="101" started-at="2017-09-07T09:23:11Z" finished-at="2017-09-07T09:23:11Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="101" started-at="2017-09-07T09:23:11Z" finished-at="2017-09-07T09:23:11Z">
      <class name="com.group.MavenTestProject.MavenTestProject.NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.group.MavenTestProject.MavenTestProject.NewTest@3a82f6ef]" name="beforeTest" is-config="true" duration-ms="26" started-at="2017-09-07T09:23:11Z" finished-at="2017-09-07T09:23:11Z">
        </test-method>
        <test-method status="FAIL" signature="f()[pri:0, instance:com.group.MavenTestProject.MavenTestProject.NewTest@3a82f6ef]" name="f" duration-ms="35" started-at="2017-09-07T09:23:11Z" finished-at="2017-09-07T09:23:11Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/google/common/base/Function]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/google/common/base/Function
	at com.group.MavenTestProject.MavenTestProject.NewTest.f(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Function
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.group.MavenTestProject.MavenTestProject.NewTest@3a82f6ef]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-09-07T09:23:11Z" finished-at="2017-09-07T09:23:11Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
